version: 2.1

jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Running the tests
          command: lein test

workflows:
  version: 2
  run_the_tests:
    jobs:
      - test